### ISSUE TITLE
Use elFinder without XML configuration

### ISSUE THREAD

**Issue by marty30** [bluejoe2008/elfinder-2.x-servlet#19]
Wouldn't it be nice to use elFinder by just adding a maven depency and a single initialisation in the code, so without all the xml-config? Spring can work without them.

I am not sure if this is something you want, but just a suggestion

**Comment by bluejoe2008** [comment]
good suggestion!

a new servlet named 'cn.bluejoe.elfinder.servlet.ConnectorServlet' is now provided
the necessary work is to configure ConnectorServlet as your connector servlet in web.xml

```
    <servlet>
        <servlet-name>elfinder-connector-servlet</servlet-name>
        <servlet-class>cn.bluejoe.elfinder.servlet.ConnectorServlet
        </servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>elfinder-connector-servlet</servlet-name>
        <url-pattern>/elfinder-servlet/connector</url-pattern>
    </servlet-mapping>
```

no additional XML configuration files are required
but,
you have to define a new servlet class derived from ConnectorServlet if you want to modify the default behaviors, instead of simply updating the XML files.

**Comment by ExtremeYu** [comment]
that's the improvement of the elfinder which provided by other author named trutssystem
